// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="FMPadding_Batch_1_FMPadding_Batch_1,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.576000,HLS_SYN_LAT=651,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=54,HLS_SYN_LUT=354,HLS_VERSION=2022_1}" *)

module FMPadding_Batch_1 (
        ap_clk,
        ap_rst_n,
        in0_V_TVALID,
        out_V_TREADY,
        in0_V_TDATA,
        in0_V_TREADY,
        out_V_TDATA,
        out_V_TVALID
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter2_fsm_state3 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;
parameter    ap_ST_iter2_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst_n;
input   in0_V_TVALID;
input   out_V_TREADY;
input  [15:0] in0_V_TDATA;
output   in0_V_TREADY;
output  [15:0] out_V_TDATA;
output   out_V_TVALID;

 reg    ap_rst_n_inv;
reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
wire   [0:0] icmp_ln279_fu_166_p2;
wire   [0:0] select_ln280_fu_268_p3;
reg    ap_predicate_op49_read_state1;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [1:0] ap_CS_iter1_fsm;
reg   [0:0] icmp_ln279_reg_386;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state2_io;
wire    ap_CS_iter1_fsm_state2;
reg   [1:0] ap_CS_iter2_fsm;
reg   [0:0] icmp_ln279_reg_386_pp0_iter1_reg;
wire    regslice_both_out_V_U_apdone_blk;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_state3_io;
wire    ap_CS_iter2_fsm_state3;
reg    ap_condition_exit_pp0_iter0_stage0;
reg    ap_ready_int;
reg    in0_V_TDATA_blk_n;
reg    out_V_TDATA_blk_n;
reg   [0:0] select_ln280_reg_390;
wire   [0:0] select_ln280_reg_390_pp0_iter0_reg;
reg   [15:0] tmp_reg_394;
reg   [15:0] ap_phi_mux_outData_1_phi_fu_105_p4;
wire   [15:0] ap_phi_reg_pp0_iter1_outData_1_reg_101;
reg   [3:0] simd_fu_68;
wire   [3:0] simd_1_fu_302_p3;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_simd_load_1;
reg   [3:0] ap_sig_allocacmp_simd_load;
reg   [3:0] x_fu_72;
wire   [3:0] select_ln280_1_fu_276_p3;
reg   [3:0] ap_sig_allocacmp_x_1;
reg   [7:0] indvar_flatten_fu_76;
wire   [7:0] select_ln280_2_fu_316_p3;
reg   [7:0] ap_sig_allocacmp_indvar_flatten_load_1;
reg   [7:0] ap_sig_allocacmp_indvar_flatten_load;
reg   [3:0] y_fu_80;
wire   [3:0] select_ln279_2_fu_242_p3;
reg   [3:0] ap_sig_allocacmp_y_1;
reg   [9:0] indvar_flatten18_fu_84;
wire   [9:0] add_ln279_fu_172_p2;
reg   [9:0] ap_sig_allocacmp_indvar_flatten18_load;
wire   [0:0] empty_8_fu_154_p2;
wire   [0:0] empty_fu_148_p2;
wire   [0:0] icmp_ln280_fu_184_p2;
wire   [3:0] add_ln279_1_fu_198_p2;
wire   [0:0] p_mid110_fu_204_p2;
wire   [0:0] or_cond_i_i_fu_160_p2;
wire   [0:0] icmp_ln281_fu_230_p2;
wire   [0:0] xor_ln279_fu_224_p2;
wire   [3:0] select_ln279_fu_190_p3;
wire   [3:0] x_3_fu_250_p2;
wire   [0:0] p_mid1_fu_256_p2;
wire   [0:0] select_ln279_1_fu_210_p3;
wire   [0:0] and_ln279_fu_236_p2;
wire   [0:0] or_cond_i_i_mid1_fu_262_p2;
wire   [0:0] or_ln279_fu_218_p2;
wire   [0:0] or_ln281_fu_296_p2;
wire   [3:0] add_ln281_fu_290_p2;
wire   [7:0] add_ln280_1_fu_310_p2;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg   [1:0] ap_NS_iter2_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
reg    ap_ST_iter1_fsm_state2_blk;
reg    ap_ST_iter2_fsm_state3_blk;
wire    ap_start_int;
wire    ap_ready;
wire    ap_done;
wire    ap_continue_int;
wire    regslice_both_in0_V_U_apdone_blk;
wire   [15:0] in0_V_TDATA_int_regslice;
wire    in0_V_TVALID_int_regslice;
reg    in0_V_TREADY_int_regslice;
wire    regslice_both_in0_V_U_ack_in;
reg    out_V_TVALID_int_regslice;
wire    out_V_TREADY_int_regslice;
wire    regslice_both_out_V_U_vld_out;
reg    ap_condition_353;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_CS_iter2_fsm = 2'd1;
end

FMPadding_Batch_1_flow_control_loop_pipe_no_ap_cont flow_control_loop_pipe_no_ap_cont_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(1'b1),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(1'b0),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(1'b0)
);

FMPadding_Batch_1_regslice_both #(
    .DataWidth( 16 ))
regslice_both_in0_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in0_V_TDATA),
    .vld_in(in0_V_TVALID),
    .ack_in(regslice_both_in0_V_U_ack_in),
    .data_out(in0_V_TDATA_int_regslice),
    .vld_out(in0_V_TVALID_int_regslice),
    .ack_out(in0_V_TREADY_int_regslice),
    .apdone_blk(regslice_both_in0_V_U_apdone_blk)
);

FMPadding_Batch_1_regslice_both #(
    .DataWidth( 16 ))
regslice_both_out_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(ap_phi_mux_outData_1_phi_fu_105_p4),
    .vld_in(out_V_TVALID_int_regslice),
    .ack_in(out_V_TREADY_int_regslice),
    .data_out(out_V_TDATA),
    .vld_out(regslice_both_out_V_U_vld_out),
    .ack_out(out_V_TREADY),
    .apdone_blk(regslice_both_out_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
    end else begin
        ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_353)) begin
        if ((icmp_ln279_fu_166_p2 == 1'd0)) begin
            indvar_flatten18_fu_84 <= add_ln279_fu_172_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten18_fu_84 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_353)) begin
        if ((icmp_ln279_fu_166_p2 == 1'd0)) begin
            indvar_flatten_fu_76 <= select_ln280_2_fu_316_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_76 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_353)) begin
        if ((icmp_ln279_fu_166_p2 == 1'd0)) begin
            simd_fu_68 <= simd_1_fu_302_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            simd_fu_68 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_353)) begin
        if ((icmp_ln279_fu_166_p2 == 1'd0)) begin
            x_fu_72 <= select_ln280_1_fu_276_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            x_fu_72 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_353)) begin
        if ((icmp_ln279_fu_166_p2 == 1'd0)) begin
            y_fu_80 <= select_ln279_2_fu_242_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            y_fu_80 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((icmp_ln279_reg_386_pp0_iter1_reg == 1'd0) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln279_reg_386 == 1'd0) & (out_V_TREADY_int_regslice == 1'b0)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op49_read_state1 == 1'b1))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        icmp_ln279_reg_386 <= icmp_ln279_fu_166_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state2_io) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((icmp_ln279_reg_386_pp0_iter1_reg == 1'd0) & (out_V_TREADY_int_regslice == 1'b0)))) | ((icmp_ln279_reg_386 == 1'd0) & (out_V_TREADY_int_regslice == 1'b0))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        icmp_ln279_reg_386_pp0_iter1_reg <= icmp_ln279_reg_386;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((icmp_ln279_reg_386_pp0_iter1_reg == 1'd0) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln279_reg_386 == 1'd0) & (out_V_TREADY_int_regslice == 1'b0)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op49_read_state1 == 1'b1))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln279_fu_166_p2 == 1'd0))) begin
        select_ln280_reg_390 <= select_ln280_fu_268_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((icmp_ln279_reg_386_pp0_iter1_reg == 1'd0) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln279_reg_386 == 1'd0) & (out_V_TREADY_int_regslice == 1'b0)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op49_read_state1 == 1'b1))) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_predicate_op49_read_state1 == 1'b1))) begin
        tmp_reg_394 <= in0_V_TDATA_int_regslice;
    end
end

always @ (*) begin
    if (((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op49_read_state1 == 1'b1))) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state2_io) | ((icmp_ln279_reg_386 == 1'd0) & (out_V_TREADY_int_regslice == 1'b0)))) begin
        ap_ST_iter1_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_iter1_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((icmp_ln279_reg_386_pp0_iter1_reg == 1'd0) & (out_V_TREADY_int_regslice == 1'b0)))) begin
        ap_ST_iter2_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_iter2_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((icmp_ln279_reg_386_pp0_iter1_reg == 1'd0) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln279_reg_386 == 1'd0) & (out_V_TREADY_int_regslice == 1'b0)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op49_read_state1 == 1'b1))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln279_fu_166_p2 == 1'd1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln279_reg_386 == 1'd0)) begin
        if ((select_ln280_reg_390_pp0_iter0_reg == 1'd1)) begin
            ap_phi_mux_outData_1_phi_fu_105_p4 = 16'd0;
        end else if ((select_ln280_reg_390_pp0_iter0_reg == 1'd0)) begin
            ap_phi_mux_outData_1_phi_fu_105_p4 = tmp_reg_394;
        end else begin
            ap_phi_mux_outData_1_phi_fu_105_p4 = ap_phi_reg_pp0_iter1_outData_1_reg_101;
        end
    end else begin
        ap_phi_mux_outData_1_phi_fu_105_p4 = ap_phi_reg_pp0_iter1_outData_1_reg_101;
    end
end

always @ (*) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((icmp_ln279_reg_386_pp0_iter1_reg == 1'd0) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln279_reg_386 == 1'd0) & (out_V_TREADY_int_regslice == 1'b0)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op49_read_state1 == 1'b1))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten18_load = 10'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten18_load = indvar_flatten18_fu_84;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten_load = 8'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_76;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten_load_1 = 8'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load_1 = indvar_flatten_fu_76;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_simd_load = 4'd0;
    end else begin
        ap_sig_allocacmp_simd_load = simd_fu_68;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_simd_load_1 = 4'd0;
    end else begin
        ap_sig_allocacmp_simd_load_1 = simd_fu_68;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_x_1 = 4'd0;
    end else begin
        ap_sig_allocacmp_x_1 = x_fu_72;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_y_1 = 4'd0;
    end else begin
        ap_sig_allocacmp_y_1 = y_fu_80;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_predicate_op49_read_state1 == 1'b1))) begin
        in0_V_TDATA_blk_n = in0_V_TVALID_int_regslice;
    end else begin
        in0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((icmp_ln279_reg_386_pp0_iter1_reg == 1'd0) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln279_reg_386 == 1'd0) & (out_V_TREADY_int_regslice == 1'b0)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op49_read_state1 == 1'b1))) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_predicate_op49_read_state1 == 1'b1))) begin
        in0_V_TREADY_int_regslice = 1'b1;
    end else begin
        in0_V_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln279_reg_386_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_iter2_fsm_state3)) | ((icmp_ln279_reg_386 == 1'd0) & (1'b1 == ap_CS_iter1_fsm_state2)))) begin
        out_V_TDATA_blk_n = out_V_TREADY_int_regslice;
    end else begin
        out_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state2_io) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((icmp_ln279_reg_386_pp0_iter1_reg == 1'd0) & (out_V_TREADY_int_regslice == 1'b0)))) | ((icmp_ln279_reg_386 == 1'd0) & (out_V_TREADY_int_regslice == 1'b0))) & (icmp_ln279_reg_386 == 1'd0) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        out_V_TVALID_int_regslice = 1'b1;
    end else begin
        out_V_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~((1'b1 == ap_block_state2_io) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((icmp_ln279_reg_386_pp0_iter1_reg == 1'd0) & (out_V_TREADY_int_regslice == 1'b0)))) | ((icmp_ln279_reg_386 == 1'd0) & (out_V_TREADY_int_regslice == 1'b0))) & ~((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op49_read_state1 == 1'b1)) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((~((1'b1 == ap_block_state2_io) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((icmp_ln279_reg_386_pp0_iter1_reg == 1'd0) & (out_V_TREADY_int_regslice == 1'b0)))) | ((icmp_ln279_reg_386 == 1'd0) & (out_V_TREADY_int_regslice == 1'b0))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & (in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op49_read_state1 == 1'b1))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((icmp_ln279_reg_386_pp0_iter1_reg == 1'd0) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln279_reg_386 == 1'd0) & (out_V_TREADY_int_regslice == 1'b0)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op49_read_state1 == 1'b1))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter2_fsm)
        ap_ST_iter2_fsm_state3 : begin
            if ((~((1'b1 == ap_block_state2_io) | ((icmp_ln279_reg_386 == 1'd0) & (out_V_TREADY_int_regslice == 1'b0))) & ~((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((icmp_ln279_reg_386_pp0_iter1_reg == 1'd0) & (out_V_TREADY_int_regslice == 1'b0))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else if ((~((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((icmp_ln279_reg_386_pp0_iter1_reg == 1'd0) & (out_V_TREADY_int_regslice == 1'b0))) & ((1'b0 == ap_CS_iter1_fsm_state2) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln279_reg_386 == 1'd0) & (out_V_TREADY_int_regslice == 1'b0))))))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end else if ((~((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((icmp_ln279_reg_386_pp0_iter1_reg == 1'd0) & (out_V_TREADY_int_regslice == 1'b0))) & (icmp_ln279_reg_386_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter2_fsm = ap_ST_iter0_fsm_state1;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end
        end
        ap_ST_iter2_fsm_state0 : begin
            if ((~((1'b1 == ap_block_state2_io) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((icmp_ln279_reg_386_pp0_iter1_reg == 1'd0) & (out_V_TREADY_int_regslice == 1'b0)))) | ((icmp_ln279_reg_386 == 1'd0) & (out_V_TREADY_int_regslice == 1'b0))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter2_fsm = 'bx;
        end
    endcase
end

assign add_ln279_1_fu_198_p2 = (ap_sig_allocacmp_y_1 + 4'd1);

assign add_ln279_fu_172_p2 = (ap_sig_allocacmp_indvar_flatten18_load + 10'd1);

assign add_ln280_1_fu_310_p2 = (ap_sig_allocacmp_indvar_flatten_load + 8'd1);

assign add_ln281_fu_290_p2 = (ap_sig_allocacmp_simd_load + 4'd1);

assign and_ln279_fu_236_p2 = (xor_ln279_fu_224_p2 & icmp_ln281_fu_230_p2);

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

assign ap_CS_iter2_fsm_state3 = ap_CS_iter2_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op49_read_state1 == 1'b1));
end

always @ (*) begin
    ap_block_state2_io = ((icmp_ln279_reg_386 == 1'd0) & (out_V_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((icmp_ln279_reg_386 == 1'd0) & (out_V_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state3_io = ((icmp_ln279_reg_386_pp0_iter1_reg == 1'd0) & (out_V_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((regslice_both_out_V_U_apdone_blk == 1'b1) | ((icmp_ln279_reg_386_pp0_iter1_reg == 1'd0) & (out_V_TREADY_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_condition_353 = (~(((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((icmp_ln279_reg_386_pp0_iter1_reg == 1'd0) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln279_reg_386 == 1'd0) & (out_V_TREADY_int_regslice == 1'b0)))) | ((in0_V_TVALID_int_regslice == 1'b0) & (ap_predicate_op49_read_state1 == 1'b1))) & (1'b1 == ap_CS_iter0_fsm_state1));
end

assign ap_phi_reg_pp0_iter1_outData_1_reg_101 = 'bx;

always @ (*) begin
    ap_predicate_op49_read_state1 = ((select_ln280_fu_268_p3 == 1'd0) & (icmp_ln279_fu_166_p2 == 1'd0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign empty_8_fu_154_p2 = (($signed(ap_sig_allocacmp_x_1) < $signed(4'd1)) ? 1'b1 : 1'b0);

assign empty_fu_148_p2 = (($signed(ap_sig_allocacmp_y_1) < $signed(4'd1)) ? 1'b1 : 1'b0);

assign icmp_ln279_fu_166_p2 = ((ap_sig_allocacmp_indvar_flatten18_load == 10'd648) ? 1'b1 : 1'b0);

assign icmp_ln280_fu_184_p2 = ((ap_sig_allocacmp_indvar_flatten_load_1 == 8'd72) ? 1'b1 : 1'b0);

assign icmp_ln281_fu_230_p2 = ((ap_sig_allocacmp_simd_load_1 == 4'd8) ? 1'b1 : 1'b0);

assign in0_V_TREADY = regslice_both_in0_V_U_ack_in;

assign or_cond_i_i_fu_160_p2 = (empty_fu_148_p2 | empty_8_fu_154_p2);

assign or_cond_i_i_mid1_fu_262_p2 = (select_ln279_1_fu_210_p3 | p_mid1_fu_256_p2);

assign or_ln279_fu_218_p2 = (or_cond_i_i_fu_160_p2 | icmp_ln280_fu_184_p2);

assign or_ln281_fu_296_p2 = (icmp_ln280_fu_184_p2 | and_ln279_fu_236_p2);

assign out_V_TVALID = regslice_both_out_V_U_vld_out;

assign p_mid110_fu_204_p2 = (($signed(add_ln279_1_fu_198_p2) < $signed(4'd1)) ? 1'b1 : 1'b0);

assign p_mid1_fu_256_p2 = (($signed(x_3_fu_250_p2) < $signed(4'd1)) ? 1'b1 : 1'b0);

assign select_ln279_1_fu_210_p3 = ((icmp_ln280_fu_184_p2[0:0] == 1'b1) ? p_mid110_fu_204_p2 : empty_fu_148_p2);

assign select_ln279_2_fu_242_p3 = ((icmp_ln280_fu_184_p2[0:0] == 1'b1) ? add_ln279_1_fu_198_p2 : ap_sig_allocacmp_y_1);

assign select_ln279_fu_190_p3 = ((icmp_ln280_fu_184_p2[0:0] == 1'b1) ? 4'd0 : ap_sig_allocacmp_x_1);

assign select_ln280_1_fu_276_p3 = ((and_ln279_fu_236_p2[0:0] == 1'b1) ? x_3_fu_250_p2 : select_ln279_fu_190_p3);

assign select_ln280_2_fu_316_p3 = ((icmp_ln280_fu_184_p2[0:0] == 1'b1) ? 8'd1 : add_ln280_1_fu_310_p2);

assign select_ln280_fu_268_p3 = ((and_ln279_fu_236_p2[0:0] == 1'b1) ? or_cond_i_i_mid1_fu_262_p2 : or_ln279_fu_218_p2);

assign select_ln280_reg_390_pp0_iter0_reg = select_ln280_reg_390;

assign simd_1_fu_302_p3 = ((or_ln281_fu_296_p2[0:0] == 1'b1) ? 4'd1 : add_ln281_fu_290_p2);

assign x_3_fu_250_p2 = (select_ln279_fu_190_p3 + 4'd1);

assign xor_ln279_fu_224_p2 = (icmp_ln280_fu_184_p2 ^ 1'd1);

endmodule //FMPadding_Batch_1
